baseURL = "https://ewingard.xyz/"
languageCode = "en-us"
title = "Ezra's Portfolio"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Ezra M. Wingard"
  description = "In solitude, where we are least alone."
  github = "ewingard"
  linkedin = "ewingard"
  email = "emwingard07@gmail.com"
  url = "https://ewingard.xyz"
  keywords = "psychology, cognitive science"
  rss = true
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/images/github.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/GitHub-Mark-Light-32px.png"
  location = "South Carolina"
  enableGitalk = true

  [[params.links]]
    title = "Link"
    href = "https://github.com/ewingard"
[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]