baseURL = "https://ewingard.xyz/"
languageCode = "en-us"
title = "Ezra's Portfolio"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Ezra M. Wingard"
  description = "On peut allumer des dizaines de bougies à partir d'une seule sans en abréger la vie. On ne diminue pas le bonheur en le partageant."
  github = "ewingard"
  linkedin = "ewingard"
  email = "emwingard07@gmail.com"
  url = "https://ewingard.xyz"
  keywords = "psychology, cognitive science"
  rss = true
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/images/github.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/GitHub-Mark-Light-32px.png"
  location = "South Carolina"
  enableGitalk = true

  [[params.links]]
    title = "Link"
    href = "https://github.com/ewingard"
    
[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]